Conversion to webextension format
Rudloff/emoji-everywhere pull request #9
Opened 2017-08-07 15:10 UTC by Schrikvis

I tried my best to keep your toolchain working, but frankly I've probably messed everything up entirely. 😔

2017-08-07 16:00 UTC, Rudloff requested changes
Thanks a lot, that's a great start!
I added a few comments to your changes. Some are required to make the add-on work correctly and others are just some good practices stuff.

Please tell me if you don't feel confortable doing some of the changes, I can do them myself if you prefer, since you already did most of the work.

2017-08-07 16:00 UTC, Rudloff commented on package.json
> -{
Is there any particular reason to delete package.json? We still need it in order to install the Grunt tasks.

2017-08-07 16:00 UTC, Rudloff commented on data/js/emoji.js
> +-/*jslint browser: true, devel: true*/
You have some buggy hyphens at the start of the lines here.

2017-08-07 16:00 UTC, Rudloff commented on data/js/twemoji.min.js
> +/*! Copyright Twitter Inc. and other contributors. Licensed under MIT */
Please don't include `twemoji.min.js` in the repository. It is cleaner to install it with Bower.

2017-08-07 16:00 UTC, Rudloff commented on manifest.json
> +  "devDependencies": {
We don't need the following properties in `manifest.json`:
* `bugs`
* `devDependencies`
* `keywords`
* `license`
* `main`
* `repository`

2017-08-07 16:00 UTC, Rudloff commented on data/js/emoji.js
>  } else {
`self` does not exist anymore in webextensions. But we can do something like this:
```js
twemoji.base = browser.extension.getURL('data/components/twemoji/2/');
```

2017-08-07 16:00 UTC, Rudloff commented on manifest.json
> +  ],
We will also need something like this in order to allow the add-on to load the images:
```json
"web_accessible_resources": [
  "data/components/twemoji/2/72x72/*.png"
],
```

2017-08-07 16:00 UTC, Rudloff commented on manifest.json
> +	    "data/js/twemoji.min.js",
Please use the one installed by Bower in `data/components/twemoji/2/twemoji.min.js`.

2017-08-17 11:45 UTC, Schrikvis commented on package.json
> -{
I was worried it'd confuse firefox about the nature of the extension, but that's nonsense and it's back now, sorry.

2017-08-17 11:50 UTC, Schrikvis commented
Take two, I think I've made all the necessary changes.

2017-08-17 12:05 UTC, Rudloff requested changes
Thanks again, everything looks good!
Just one final little change and then I will merge: now that package.json is back, can you please restore the fixpack task in Gruntfile.js?

2017-08-18 08:40 UTC, Rudloff approved these changes

2017-08-18 08:41 UTC, merged

2017-08-28 00:57 UTC, Schrikvis commented
❤